server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:5500/order_service?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  application:
    name: order-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:admin@localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10 #store maximum 10 events at a time
        failureRateThreshold: 50
        minimumNumberOfCalls: 5 #if less 5 events status is not open
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10 #outcomes of last 10 requests is tracking, older request is drop out
        slidingWindowType: COUNT_BASED
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s # time between 2 attempt is 5s