server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:5500/order_service?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  application:
    name: order-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:admin@localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enable: true
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: "ALWAYS"

##Resilinece4j properties
  resilience4j:
    circuitbreaker:
      instances:
        inventory:
          registerHealthIndicator: true
          event-consumer-buffer-size: 10
          slidingWindowType: COUNT_BASED
          slidingWindowSize: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 5s
          permittedNumberOfCallsInHalfOpenState: 3
          automaticTransitionFromOpenToHalfOpenEnabled: true