eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:admin@localhost:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices.product
  application:
    name: product-service

server:
  port: 0